bloom_enabled = true
bloom_intensity = 2.023
bloom_iterations = 3
bloom_downsample = 2
bloom_blur_method = "Kawase"
tone_mapping_mode = "ACES"
render_rockets = true
render_smoke = true
render_trails = true
render_explosions = true
