[book]
title = "Fireworks Simulator Documentation"
authors = ["Lionel ATTY"]
description = "Documentation and performance profiling guides for the Rust Fireworks Simulator."
src = "doc"

[output.html]
theme = "doc/theme"
git-repository-url = "https://github.com/yoyonel/rust-firework"
default-theme = "navy"
preferred-dark-theme = "navy"
mathjax-support = true
