name: Preview mdBook Documentation (Surge.sh)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "doc/**"
      - "book.toml"
      - ".github/workflows/preview_docs.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    name: Build & Deploy mdBook Surge Preview
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yoyonel/rust-firework-ci:latest
      options: --user root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build mdBook Documentation
        run: mdbook build

      - name: Deploy Surge PR Preview & Comment
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          build: echo "skip build"
          dist: ./book
          teardown: false
